module.exports = {
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  CONNECT: "connection",
  DISCONNECT: "disconnect",
  USER_CONNECTED: "USER_CONNECTED",
  TYPING: "TYPING",
  GENERAL_CHAT: "GENERAL_CHAT",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
};