module.exports = {
  MESSAGE_SENT: "MESSAGE_SENT",
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  CONNECT: "connection",
  DISCONNECT: "disconnect",
  USER_CONNECTED: "USER_CONNECTED",
  USER_DISCONNECTED: "USER_DISCONNECTED",
  TYPING: "TYPING",
  PRIVATE_MESSAGE: "PRIVATE_MESSAGE",
  LOGOUT: "LOGOUT",
};